# Site settings
title: 0x2C
email: reach.zuripabon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just my little corner where start tuning my innate literacy talent ;)
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "https://zuripabon.es" # the base hostname & protocol for your site
twitter_username: zuripabon
github_username:  zuripabon
highlighter: pygments
# Build settings
markdown: kramdown
